Added useful contract addresses
matter-labs/zksync-web-era-docs pull request #332
Opened 2023-03-16 18:50 UTC by krofax

Added useful contract addresses for testnet and mainnet

2023-03-20 12:14 UTC, githubdoramon requested changes
- You are mixing addresses with root hashes... Please remove the later or add as a separate section
- Why not adding etherscan/explorer links to all contracts?
- This section makes more sense under Building on zkSync,not troubleshooting

2023-03-21 16:57 UTC, krofax commented
> https://aqwzx-zksync-v2-docs--pr332-usefull-addresses-nci4mmtu.web.app

Is there a way to link root hashes, e.g - 0xbc59c242d551e3939b9b2939b8b686efa77ba3833183045d548aa5f53357ba95

2023-03-21 17:14 UTC, githubdoramon requested changes
Needs some changes... and you linked L2 contracts to etherscan instead of our explorer

2023-03-21 17:14 UTC, githubdoramon commented on docs/dev/building-on-zksync/useful-address.md
> +_Users should only interact with the token bridge contracts via [zkSync portal](https://portal.zksync.io/) or any other dapp._
zkSync Bridge (bridge.zksync.io) or zkSync Portal (portal.zksync.io)

2023-03-21 17:14 UTC, githubdoramon commented on docs/dev/building-on-zksync/useful-address.md
> +## Token request
Known tokens

2023-03-21 17:14 UTC, githubdoramon commented on docs/dev/building-on-zksync/useful-address.md
> +|      Contract names           | zkSync Era Mainnet                                                 |
Contract Name | Address

2023-03-21 17:14 UTC, githubdoramon commented on docs/dev/building-on-zksync/useful-address.md
> +|       Contract names          | zkSync Era Mainnet                                                 |
Name | Hash

2023-03-21 17:14 UTC, githubdoramon commented on docs/dev/building-on-zksync/useful-address.md
> +|      Contract names           | Contracts                                                                                                                 |
Contract Name | Address

2023-03-21 17:14 UTC, githubdoramon commented on docs/dev/building-on-zksync/useful-address.md
> +|      Contract names           | L1                                                                                                                               |
Contract Name | Address

2023-03-21 17:14 UTC, githubdoramon commented on docs/dev/building-on-zksync/useful-address.md
> +|                               | zkSync Era Testnet                                                 |
Name | Hash

2023-03-21 17:14 UTC, githubdoramon commented on docs/dev/building-on-zksync/useful-address.md
> +|      Contract names           | Contracts                                                                                                                          |
Contract Name | Address

2023-03-21 17:14 UTC, githubdoramon commented on docs/dev/building-on-zksync/useful-address.md
> +| l2_testnet_paymaster_addr     | [0x0265d9a5af8af5fe070933e5e549d8fef08e09f4](https://etherscan.io/address/0x0265d9a5af8af5fe070933e5e549d8fef08e09f4#code)|
how can the testnet paymaster be on mainnet addresses?

2023-03-22 09:52 UTC, githubdoramon requested changes

2023-03-22 09:52 UTC, githubdoramon commented on docs/dev/building-on-zksync/useful-address.md
> +| l2_mainnet_paymaster_addr     | [0x0265d9a5af8af5fe070933e5e549d8fef08e09f4](https://goerli.explorer.zksync.io/address/0x0265d9a5af8af5fe070933e5e549d8fef08e09f4)|
@krofax there is no mainnet paymaster, and especially not pointing to a goerli address. Just remove this line

2023-03-22 09:52 UTC, githubdoramon commented on docs/dev/building-on-zksync/useful-address.md
> +|      Contract Name            | L1 Address                                                                                                                       |
Remove the L1 and make consitent to others

2023-03-22 09:52 UTC, githubdoramon commented on docs/dev/building-on-zksync/useful-address.md
> +| l2_testnet_paymaster_addr     | [0x8f0ea1312da29f17eabeb2f484fd3c112cccdd63](https://goerli.explorer.zksync.io/address/0x8f0ea1312da29f17eabeb2f484fd3c112cccdd63)|
Why removing the #contract?

2023-03-22 12:56 UTC, githubdoramon commented on docs/dev/building-on-zksync/useful-address.md
> +## Known tokens
@krofax pls add token name and symbol (same ones available at Etherescan on L1)

2023-03-22 16:29 UTC, merged