WIP demo suggestions
matter-labs/zksync-web-era-docs pull request #432
Opened 2023-04-18 15:07 UTC by kailash-manasarovar

2023-04-18 15:24 UTC, krofax requested changes

2023-04-18 15:24 UTC, krofax commented on docs/.vuepress/sidebar/en.ts
> +      children: ["/dev/fundamentals/lorem.md", "/dev/fundamentals/rollups.md", "/dev/fundamentals/zkSync.md", "/dev/fundamentals/interacting.md", "/dev/fundamentals/hyperscaling.md"],
```suggestion
      children: ["/dev/fundamentals/lorem.md", "/dev/fundamentals/rollups.md", "/dev/fundamentals/zkSync-basics.md", "/dev/fundamentals/interacting.md", "/dev/fundamentals/hyperscaling.md"],
```

2023-04-18 15:24 UTC, krofax commented on docs/dev/fundamentals/lorem.md
> +- Ad liber scripserit philosophia his.
```suggestion
- Bonorum torquatos sententiae vim et, mea omnium tabiture assentior id. 
- Ad liber scripserit philosophia his. 
```

2023-04-18 15:24 UTC, krofax commented on docs/dev/fundamentals/lorem.md
> +Sea veniam inimicus delicatissimi te. Vis in iisque alterum expetendis, quo impedit adipisci te. Ne sonet zril signiferumque per, per verear aliquid deterruisset id.
```suggestion
Sea veniam pasmiscusd limitations te. Vis in iisque alterum expetendis, quo impedit adipisci te. Ne sonet zril signiferumque per, per verear aliquid deterruisset id.
```

2023-04-19 15:38 UTC, kailash-manasarovar commented
Closing after demo.

2023-04-19 15:38 UTC, closed without merging