Added bridging script
matter-labs/zksync-web-era-docs pull request #433
Opened 2023-04-18 15:35 UTC by krofax

Added bridging script to deposit ETH and ERC20 tokens to L2.

2023-04-18 16:12 UTC, uF4No commented on docs/dev/developer-guides/bridging/bridging-asset.md
>  :::
I'd move this warning before the scripts as it was part of the original text

2023-04-18 16:13 UTC, uF4No commented
Can we add an info message to let users know about the withdrawal delay in the "Withdrawals (to L1)" section?

2023-04-18 16:13 UTC, uF4No commented on docs/dev/developer-guides/bridging/bridging-asset.md
> +#### Deposit ETH
```suggestion
### Deposit ETH
```

2023-04-18 16:14 UTC, uF4No commented on docs/dev/developer-guides/bridging/bridging-asset.md
> +#### Deposit ERC20 tokens
```suggestion
### Deposit ERC20 tokens
```

2023-04-19 07:07 UTC, kailash-manasarovar commented on docs/dev/developer-guides/bridging/bridging-asset.md
> +To run this script, configure your `hardhat.config.ts` file as explained in this [guide](../../../api/hardhat/hardhat-zksync-deploy.md), or use the command `npx zksync-cli@latest create PROJECT_NAME`
```suggestion
To run this script, configure your `hardhat.config.ts` file as explained in this [guide](../../../api/hardhat/hardhat-zksync-deploy.md), or use the command `npx zksync-cli@latest create PROJECT_NAME` to scaffold a new project.
```

2023-04-19 07:08 UTC, kailash-manasarovar commented on docs/dev/developer-guides/bridging/bridging-asset.md
> +If you have your `hardhat.config.ts` file, configure, place the script files in the `deploy` folder and run:
```suggestion
Once your `hardhat.config.ts` file is configured, place the script files in the `deploy` folder and run them with the following command:
```

2023-04-19 07:09 UTC, kailash-manasarovar commented on docs/dev/developer-guides/bridging/bridging-asset.md
> +Withdrawals in zkSync Era take **24 hours**, to learn about withdrawal delay, see this [guide](../../troubleshooting/withdrawal-delay.md)
```suggestion
- Withdrawals in zkSync Era take **24 hours**.
- For more information, read the [withdrawal delay guide](../../troubleshooting/withdrawal-delay.md).
```

2023-04-19 07:11 UTC, kailash-manasarovar commented on docs/dev/troubleshooting/changelog.md
> +- `hardhat-zksync-verify` version `0.1.2`: now returns a verification id, which can be used to query the status of a smart contract verification. More info [here](../../api/hardhat/hardhat-zksync-ver
```suggestion
- `hardhat-zksync-verify` version `0.1.2`: now returns a verification id. Use this to query the status of smart contract verification. For more information, read the [Hardhat zkSync Era verification doc](../../api/hardhat/hardhat-zksync-verify.md#verification-status-check)
```

2023-04-19 07:11 UTC, kailash-manasarovar requested changes
A few small things.

2023-04-19 08:59 UTC, uF4No commented on docs/dev/developer-guides/bridging/bridging-asset.md
> +Withdrawals in zkSync Era take **24 hours**, to learn about withdrawal delay, see this [guide](../../troubleshooting/withdrawal-delay.md)
```suggestion
To provide additional security during the Alpha phase, **withdrawals in zkSync Era take 24 hours**. For more information, read the [withdrawal delay guide](../../troubleshooting/withdrawal-delay.md).
```

2023-04-19 13:11 UTC, krofax commented
@kailash-manasarovar can you approve?

2023-04-19 13:14 UTC, kailash-manasarovar approved these changes
SGTM.

2023-04-19 14:16 UTC, merged