fix broken links
matter-labs/zksync-web-era-docs pull request #439
Opened 2023-04-19 14:16 UTC by krofax

2023-04-19 14:44 UTC, kailash-manasarovar commented on docs/api/js/getting-started.md
> +- For more information, read the [changelog](../../dev/troubleshooting/changelog.md#hardhat-plugins-update-feb-24th-2023).
I don't think this is broken.

2023-04-19 14:44 UTC, kailash-manasarovar commented on docs/dev/developer-guides/bridging/l1-l2.md
> +- For more information, read the [changelog](../../troubleshooting/changelog.md#hardhat-plugins-update-feb-24th-2023).
I don't think this is broken either.

2023-04-19 14:45 UTC, kailash-manasarovar commented on docs/dev/developer-guides/bridging/l2-l1.md
> +- For more information, read the [changelog](../../troubleshooting/changelog.md#hardhat-plugins-update-feb-24th-2023).
I don't think this is broken.

2023-04-19 14:47 UTC, kailash-manasarovar requested changes
The fix is of three links on the page recorded in the first column in the pic in the ticket.

2023-04-19 15:38 UTC, krofax commented
> The fix is of three links on the page recorded in the first column in the pic in the ticket.

There were broken, found out when I ran `yarn lint:dead`

2023-04-19 15:45 UTC, kailash-manasarovar commented
> 

- Yes, there are three broken links that you fixed by creating dummy pages for. That is not necessary.
- The changelog links you fixed aren't broken, for example: https://era.zksync.io/docs/api/js/getting-started.html try it.

2023-04-19 17:51 UTC, krofax commented
> > 
> 
> * Yes, there are three broken links that you fixed by creating dummy pages for. That is not necessary.
> * The changelog links you fixed aren't broken, for example: https://era.zksync.io/docs/api/js/getting-started.html try it.

- Totally agree the pages ain't necessary, I did a redirect instead(happy to know your thoughts on this). However, when we do have all the SDK revamped we should add a `README.md` file in them just like the others.

- It doesn't look broken on prod, but it does on local, it just makes sense to link properly, the `ENV`(local, staging, or prod notwithstanding). yeah?

2023-04-20 06:42 UTC, kailash-manasarovar requested changes
This is also unnecessary. The broken links are on this page: https://era.zksync.io/docs/dev/ just fix the links on this page.

2023-04-20 06:47 UTC, kailash-manasarovar commented
> > > 
> > 
> > 
> > 
> > * Yes, there are three broken links that you fixed by creating dummy pages for. That is not necessary.
> > * The changelog links you fixed aren't broken, for example: https://era.zksync.io/docs/api/js/getting-started.html try it.
> 
> * Totally agree the pages ain't necessary, I did a redirect instead(happy to know your thoughts on this). However, when we do have all the SDK revamped we should add a `README.md` file in them just like the others.

I'm not convinced a README page with nothing on it but a manual toc which we have to remember to keep up to date is a good idea.

> * It doesn't look broken on prod, but it does on local, it just makes sense to link properly, the `ENV`(local, staging, or prod notwithstanding). yeah?

I don't have the issue locally. Have you got the latest updates?

2023-04-20 06:55 UTC, kailash-manasarovar commented on docs/dev/README.md
> +- [Python SDK](../api/python/getting-started.md) - Explore all the Python methods and functions required to build on zkSync Era.
not this one

2023-04-20 07:11 UTC, kailash-manasarovar approved these changes
LGTM

2023-04-20 07:11 UTC, merged