Add warning to compiler toolchain
matter-labs/zksync-web-era-docs pull request #464
Opened 2023-04-27 10:10 UTC by krofax

Add warning to compiler toolchain page.

2023-05-02 07:51 UTC, kailash-manasarovar requested changes
Why only on this page?

Add here: https://era.zksync.io/docs/api/compiler-toolchain/
And here: https://era.zksync.io/docs/api/compiler-toolchain/vyper.html

And check with @hedgar2017 if you should add here too.

2023-05-02 07:55 UTC, hedgar2017 submitted a review, later dismissed

2023-05-05 11:43 UTC, hedgar2017 commented
> Why only on this page?
> 
> 
> 
> Add here: https://era.zksync.io/docs/api/compiler-toolchain/
> 
> And here: https://era.zksync.io/docs/api/compiler-toolchain/vyper.html
> 
> 
> 
> And check with @hedgar2017 if you should add to LLVM.

LLVM is too much because it may be unclear what version it refers too. Overview, zksolc and zkvyper must be enough.

2023-05-05 11:43 UTC, hedgar2017 approved these changes

2023-05-05 13:59 UTC, merged