update useful addresses
matter-labs/zksync-web-era-docs pull request #496
Opened 2023-05-11 13:45 UTC by krofax

Updated the useful address section, with more addresses listed on our block explorer.

2023-05-11 14:26 UTC, kailash-manasarovar commented on docs/dev/building-on-zksync/useful-address.md
> +These are the list of mainnet contract addresses that deployed on zkSync Era network.
```suggestion
```

2023-05-11 14:26 UTC, kailash-manasarovar commented on docs/dev/building-on-zksync/useful-address.md
> +These are the list of testnet contract addresses that deployed on zkSync Era network.
```suggestion
```

2023-05-11 14:26 UTC, kailash-manasarovar commented on docs/dev/building-on-zksync/useful-address.md
> +These are the addresses that have been deployed and integrated with the token bridge on testnet.
```suggestion
```

2023-05-11 14:27 UTC, kailash-manasarovar commented on docs/dev/building-on-zksync/useful-address.md
> +These are the tokens that are listed on our block explorer. Learn how to [add token](../developer-guides/bridging/bridging-asset.md#add-tokens-to-the-bridge) to our bridge.
```suggestion
These tokens are listed on our block explorer. Learn how to [add tokens to the bridge](../developer-guides/bridging/bridging-asset.md#add-tokens-to-the-bridge).
```

2023-05-11 14:28 UTC, kailash-manasarovar commented on docs/dev/building-on-zksync/useful-address.md
> +| USDC                          | USD Coin      | [0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48](https://etherscan.io/address/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48)|[0x3355df6D4c9C3035724Fd0e3914d
Should this be a verified contract link for USD Coin? I don't think it's correct.

2023-05-11 14:31 UTC, kailash-manasarovar commented on docs/dev/building-on-zksync/useful-address.md
>  ### Testnet token bridge contracts addresses
```suggestion
### Testnet token bridge, contract addresses
```

2023-05-11 14:33 UTC, kailash-manasarovar requested changes
Can you check the token addresses. I'm seeing unverified contracts for many of them and it feels incorrect.

2023-05-11 14:36 UTC, krofax commented
> Can you check the token addresses. I'm seeing unverified contracts for many of them and it feels incorrect.

If you're referring to L2, not all the tokens are verified, see here - https://explorer.zksync.io/tokenlist

2023-05-11 14:38 UTC, kailash-manasarovar commented
> > Can you check the token addresses. I'm seeing unverified contracts for many of them and it feels incorrect.
> 
> If you're referring to L2, not all the tokens are verified, see here - https://explorer.zksync.io/tokenlist

Ah OK, thank you. I'll check again in the a.m. :)

2023-05-11 14:40 UTC, kailash-manasarovar commented on docs/dev/building-on-zksync/useful-address.md
> +| USDC                          | USD Coin      | [0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48](https://etherscan.io/address/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48)|[0x3355df6D4c9C3035724Fd0e3914d
Is L1 correct?

2023-05-12 08:45 UTC, kailash-manasarovar approved these changes
OK, I trust these are correct .. I was a bit surprised they weren't verified :)

2023-05-12 10:40 UTC, merged