improves scripts adds withdraw
matter-labs/zksync-web-era-docs pull request #523
Opened 2023-05-18 17:57 UTC by uF4No

- simpler bridge scripts
- adds withdraw scripts

2023-05-26 15:13 UTC, Kylemclean11 approved these changes
0789147010

2023-05-26 15:13 UTC, Kylemclean11 approved these changes
0789147010

2023-05-26 15:14 UTC, Kylemclean11 requested changes
#523

2023-06-09 12:46 UTC, kailash-manasarovar requested changes
-> A few clarifications needed on my side.

2023-06-09 16:27 UTC, dutterbutter commented
Updated to fill in relevant details for withdraw script, however I the `Deposit ERC-20 tokens` script seems to hang for me on my side and could not get it to execute successfully. Can you confirm it runs successfully for you? @uF4No

2023-06-13 14:07 UTC, kailash-manasarovar commented on docs/dev/how-to/withdraw-via-bridge.md
> +### 3. Run the script
```suggestion
### 4. Run the script
```

2023-06-13 14:07 UTC, kailash-manasarovar commented on docs/dev/how-to/withdraw-via-bridge.md
> +### 4. Output
```suggestion
### 5. Output
```

2023-06-13 14:07 UTC, kailash-manasarovar commented on docs/dev/how-to/withdraw-via-bridge.md
> +### 3. Run the script
```suggestion
### 4. Run the script
```

2023-06-13 14:07 UTC, kailash-manasarovar commented on docs/dev/how-to/withdraw-via-bridge.md
> +### 4. Output
```suggestion
### 5. Output
```

2023-06-13 14:08 UTC, kailash-manasarovar submitted a review, later dismissed
SGTM. Sorry, I didn't test it. If anything comes back, I'll deal with it.

2023-06-16 11:01 UTC, uF4No commented on docs/dev/how-to/deposit-via-bridge.md
> +```
I don't think we need to use the CLI for this, we can just scaffold a project as mentioned above
```suggestion
```sh
mkdir deposit-erc20-script && cd deposit-erc20-script
npm init -y 
npm i typescript ts-node ethers@^5.7.2 zksync-web3 dotenv
```
```

2023-06-16 11:02 UTC, uF4No commented on docs/dev/how-to/withdraw-via-bridge.md
> +```
No need to use the CLI
```suggestion
```sh
mkdir withdraw-erc20-script && cd withdraw-erc20-script
npm init -y 
npm i typescript ts-node ethers@^5.7.2 zksync-web3 dotenv
```
```

2023-08-10 16:28 UTC, uF4No commented
@dutterbutter yeah, deposit erc20 gets stuck although the transaction appear in the L1 explorer after a few minutes. I'll try to figure out why

2023-09-07 12:49 UTC, Zionsammy approved these changes

2024-01-18 10:16 UTC, closed without merging

2024-01-18 10:16 UTC, MexicanAce commented
Closing due to inactive, stale PR