Added language translation to docs
matter-labs/zksync-web-era-docs pull request #534
Opened 2023-05-25 15:25 UTC by krofax

Added language translation to docs.

2023-05-26 07:21 UTC, kailash-manasarovar requested changes
Errors when I spin it up.
Looks good on working link.

2023-05-26 08:20 UTC, krofax commented
> Errors when I spin it up. Looks good on working link.

You probably need to run `yarn add`.

2023-05-26 08:26 UTC, kailash-manasarovar commented
OK, yarn add solved the problem. Let's check with Product team what they think.

2023-05-29 09:10 UTC, kailash-manasarovar approved these changes

2023-05-29 09:10 UTC, merged