add diff 4337 with aa
matter-labs/zksync-web-era-docs pull request #604
Opened 2023-06-20 16:09 UTC by AlbionaHoti

2023-06-20 16:42 UTC, dutterbutter requested changes
Small changes requested.

2023-06-20 16:42 UTC, dutterbutter commented on docs/reference/architecture/differences-with-ethereum.md
> +3. **Transaction Processing**: EIP 4337 introduces a separate transaction flow for smart contract accounts, which relies in a separate mempool for user operations, and Bundlers, nodes that bundle use
```suggestion
3. **Transaction Processing**: EIP 4337 introduces a separate transaction flow for smart contract accounts, which relies on a separate mempool for user operations, and Bundlers - nodes that bundle user operations and sends them to be processed by the EntryPoint contract, resulting in two separate transaction flows. In contrast, on zkSync Era there is a unified mempool for transactions from both Externally Owned Accounts (EOAs) and smart contract accounts. In zkSync Era, the Operator takes on the role of bundling transactions, irrespective of the account type, and sends them to the Bootloader (similar to the EntryPoint contract), which results in a single mempool and transaction flow.
```

2023-06-21 09:05 UTC, uF4No approved these changes
LGTM

2023-06-21 14:26 UTC, uF4No approved these changes

2023-06-21 15:07 UTC, merged