Proxy fee estimation feature, verify plugin core dependency change
matter-labs/zksync-web-era-docs pull request #615
Opened 2023-06-30 13:57 UTC by FilipTxFusion

- Add proxy fee estimation feature for the upgradable plugin
- Change verify plugin core dependency to @nomicfoundation/hardhat-verify

2023-07-04 12:00 UTC, dutterbutter requested changes
Few small changes

2023-07-04 12:00 UTC, dutterbutter commented on docs/tools/hardhat/hardhat-zksync-upgradable.md
> +If you don't want to see all the separate estimations, you can use the parameter `quiet` as the last parameter in every method and receive just the returned sum.
```suggestion
Each of these methods totals the fee for every contract in their respective pipeline, displays the cost on the console, and returns the cumulative sum. If you prefer not to see the individual estimations, introduce the parameter `quiet` as the final parameter in any method to receive only the returned sum.
```

2023-07-04 15:07 UTC, FilipTxFusion commented
> Few small changes

Agree with all of them. Committed the changes.

2023-07-04 16:34 UTC, dutterbutter commented
@FilipTxFusion please resolve conflicts and we should be good! Thanks 🙏

2023-07-05 10:34 UTC, uF4No approved these changes

2023-07-05 11:54 UTC, dutterbutter approved these changes

2023-07-05 11:54 UTC, merged