Swift documentation
matter-labs/zksync-web-era-docs pull request #626
Opened 2023-07-05 20:47 UTC by bojan-txfusion

2023-07-09 01:11 UTC, Blonde488 approved these changes
[](docs/api/swift/contracts.md)

2023-07-17 11:03 UTC, uF4No commented
@bojan-txfusion Can you also update the menu to actually display the Swift SDK? It was deleted a while ago

2023-07-17 11:19 UTC, bojan-txfusion commented
> @bojan-txfusion Can you also update the menu to actually display the Swift SDK? It was deleted a while ago

If you talk about this menu (https://github.com/matter-labs/zksync-web-era-docs/tree/swift/docs/docs/api), it was added already. If it's some other menu, just let me know which one.

2023-08-02 10:06 UTC, uF4No commented
@bojan-txfusion You'd need to add the menu items in `docs/.vuepress/sidebar/en.ts`.

2023-08-03 07:44 UTC, bojan-txfusion commented
> @bojan-txfusion You'd need to add the menu items in `docs/.vuepress/sidebar/en.ts`.

Just added.

2023-08-13 11:47 UTC, Blonde488 commented on docs/api/swift/contracts.md
hope you like this!!

2023-08-28 10:32 UTC, idea404 requested changes
A few suggestions: 
- Can the script/snippet code match what can be found in the [examples PR](https://github.com/zksync-sdk/zksync2-examples/pull/1)
- Would be nice for the sidebar & page structure of the contents of `getting-started` to follow what's been done for Go API 
- I think it would also make it easier for the example repo to include a project set up with Xcode that developers can copy locally, overwrite some config vars (as private key and RPC URLs), open on Xcode, build the simulator and click on buttons on the simulator that execute the different code snippets performing the deposit, withdraw, etc.

2023-08-30 07:38 UTC, bojan-txfusion commented on docs/api/swift/getting-started.md
> + pod 'zkSync2-swift'
Correct. Now it works since the latest version is now 0.0.2

2023-08-30 07:41 UTC, bojan-txfusion commented on docs/api/swift/getting-started.md
> +
This info would probably be redundant, so if you ask me, I would say it's not needed.

2024-01-18 16:37 UTC, closed without merging