feat: adds OG plugin
matter-labs/zksync-web-era-docs pull request #669
Opened 2023-08-17 16:10 UTC by uF4No

# What :computer: 
* First thing updated with this PR
* Second thing updated with this PR
* Third thing updated with this PR

# Why :hand:
* Reason why first thing was added to PR
* Reason why second thing was added to PR
* Reason why third thing was added to PR

# Evidence :camera:
Include screenshots, screen recordings, or `console` output here demonstrating that your changes work as intended

# Notes :memo:
* Any notes/thoughts that the reviewers should know prior to reviewing the code?

2023-08-21 11:56 UTC, idea404 requested changes
Some small changes related to grammar 
Might merit looking later into grammar of wider docs

2023-08-21 11:56 UTC, idea404 commented on docs/dev/how-to/verify-contracts.md
> +      content: Verify Contracts with Hardhat | zkSync Era docs
I think we should be consistent in how we capitalise titles, in English subtitles and titles have capital letters for almost every word like with this title. I will suggest changes for the previous titles

2023-08-21 11:56 UTC, idea404 commented on docs/api/README.md
> +      content: Web3 API & SDKs | zkSync Era docs
```suggestion
      content: Web3 API & SDKs | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/api.md
> +      content: Web3 JSON-RPC API | zkSync Era docs
```suggestion
      content: Web3 JSON-RPC API | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/go/README.md
> +      content: Go SDK | zkSync Era docs
```suggestion
      content: Go SDK | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/go/accounts-l1-l2.md
> +      content: Go SDK L1/L2 transactions | zkSync Era docs
```suggestion
      content: Go SDK L1/L2 Transactions | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/go/accounts.md
> +      content: Go SDK Accounts | zkSync Era docs
```suggestion
      content: Go SDK Accounts | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/go/clients.md
> +      content: Go SDK Clients | zkSync Era docs
```suggestion
      content: Go SDK Clients | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/go/contracts.md
> +      content: Go SDK Contracts | zkSync Era docs
```suggestion
      content: Go SDK Contracts | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/go/examples/create.md
> +      content: Go SDK create example | zkSync Era docs
```suggestion
      content: Go SDK Create Example | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/go/examples/create2.md
> +      content: Go SDK create2 example | zkSync Era docs
```suggestion
      content: Go SDK create2 Example | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/go/examples/custom-paymaster/deploy-account.md
> +      content: Go SDK deploy paymaster example | zkSync Era docs
```suggestion
      content: Go SDK Deploy Paymaster Example | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/go/examples/custom-paymaster/deploy-token.md
> +      content: Go SDK deploy token example | zkSync Era docs
```suggestion
      content: Go SDK Deploy Token Example | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/go/examples/custom-paymaster/use-paymaster.md
> +      content: Go SDK use paymaster example | zkSync Era docs
```suggestion
      content: Go SDK Use Paymaster Example | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/go/examples/deposit.md
> +      content: Go SDK deposit example | zkSync Era docs
```suggestion
      content: Go SDK Deposit Example | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/go/examples/get-confirmed-tokens.md
> +      content: Go SDK get tokens example | zkSync Era docs
```suggestion
      content: Go SDK Get Tokens Example | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/go/examples/transfer.md
> +      content: Go SDK transfer example | zkSync Era docs
```suggestion
      content: Go SDK Transfer Example | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/go/examples/withdraw.md
> +      content: Go SDK withdraw example | zkSync Era docs
```suggestion
      content: Go SDK Withdraw Example | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/go/features.md
> +      content: Go SDK features | zkSync Era docs
```suggestion
      content: Go SDK Features | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/go/getting-started.md
> +      content: Go SDK getting started | zkSync Era docs
```suggestion
      content: Go SDK Getting Started | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/go/paymaster-utils.md
> +      content: Go SDK Paymaster utilities | zkSync Era docs
```suggestion
      content: Go SDK Paymaster Utilities | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/go/types/accounts.md
> +      content: Go SDK accounts package | zkSync Era docs
```suggestion
      content: Go SDK Accounts Package | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/go/types/clients.md
> +      content: Go SDK clients package | zkSync Era docs
```suggestion
      content: Go SDK Clients Package | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/go/types/eip712.md
> +      content: Go SDK eip712 package | zkSync Era docs
```suggestion
      content: Go SDK EIP712 Package | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/go/types/intro.md
> +      content: Go SDK types | zkSync Era docs
```suggestion
      content: Go SDK Types | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/go/types/types.md
> +      content: Go SDK types package | zkSync Era docs
```suggestion
      content: Go SDK Types Package | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/go/utils.md
> +      content: Go SDK Utils | zkSync Era docs
```suggestion
      content: Go SDK Utils | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/java/README.md
> +      content: Java SDK | zkSync Era docs
```suggestion
      content: Java SDK | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/java/accounts-l1-l2.md
> +      content: Java SDK L1/L2 transactions | zkSync Era docs
```suggestion
      content: Java SDK L1/L2 Transactions | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/java/accounts.md
> +      content: Java SDK accounts | zkSync Era docs
```suggestion
      content: Java SDK Accounts | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/java/getting-started.md
> +      content: Java SDK getting started | zkSync Era docs
```suggestion
      content: Java SDK Getting Started | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/java/providers.md
> +      content: Java SDK providers | zkSync Era docs
```suggestion
      content: Java SDK Providers | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/js/README.md
> +      content: JS SDK | zkSync Era docs
```suggestion
      content: JS SDK | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/js/accounts-l1-l2.md
> +      content: JS SDK L1/L2 transactions | zkSync Era docs
```suggestion
      content: JS SDK L1/L2 Transactions | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/js/accounts.md
> +      content: JS SDK accounts | zkSync Era docs
```suggestion
      content: JS SDK Accounts | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/js/contracts.md
> +      content: JS SDK contracts | zkSync Era docs
```suggestion
      content: JS SDK Contracts | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/js/features.md
> +      content: JS SDK features | zkSync Era docs
```suggestion
      content: JS SDK Features | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/js/front-end.md
> +      content: JS SDK front-end integration | zkSync Era docs
```suggestion
      content: JS SDK Front-End Integration | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/js/getting-started.md
> +      content: JS SDK getting started | zkSync Era docs
```suggestion
      content: JS SDK Getting Started | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/js/paymaster-utils.md
> +      content: JS SDK paymaster utilities | zkSync Era docs
```suggestion
      content: JS SDK Paymaster Utilities | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/js/providers.md
> +      content: JS SDK providers | zkSync Era docs
```suggestion
      content: JS SDK Providers | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/js/types.md
> +      content: JS SDK types | zkSync Era docs
```suggestion
      content: JS SDK Types | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/js/utils.md
> +      content: JS SDK utilities | zkSync Era docs
```suggestion
      content: JS SDK Utilities | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/python/README.md
> +      content: Python SDK | zkSync Era docs
```suggestion
      content: Python SDK | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/python/accounts-l1-l2.md
> +      content: Python SDK L1/L2 transactions | zkSync Era docs
```suggestion
      content: Python SDK L1/L2 Transactions | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/python/accounts.md
> +      content: Python SDK accounts | zkSync Era docs
```suggestion
      content: Python SDK Accounts | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/python/contracts.md
> +      content: Python SDK contract | zkSync Era docs
```suggestion
      content: Python SDK Contract | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/python/getting-started.md
> +      content: Python SDK getting started | zkSync Era docs
```suggestion
      content: Python SDK Getting Started | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/python/paymaster-utils.md
> +      content: Python SDK paymaster utilities | zkSync Era docs
```suggestion
      content: Python SDK Paymaster Utilities | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/api/python/types.md
> +      content: Python SDK types | zkSync Era docs
```suggestion
      content: Python SDK Types | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/dev/README.md
> +      content: Welcome | zkSync Era docs
```suggestion
      content: Welcome | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/dev/building-on-zksync/best-practices.md
> +      content: Security and best practices | zkSync Era docs
```suggestion
      content: Security and Best Practices | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/dev/building-on-zksync/hello-world.md
> +      content: Hello world | zkSync Era docs
```suggestion
      content: Hello World | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/dev/building-on-zksync/interacting.md
> +      content: Interact with zkSync Era | zkSync Era docs
```suggestion
      content: Interact with zkSync Era | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/dev/building-on-zksync/useful-address.md
> +      content: Useful addresses | zkSync Era docs
```suggestion
      content: Useful Addresses | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/dev/how-to/README.md
> +      content: How to | zkSync Era docs
```suggestion
      content: How To | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/dev/how-to/estimate-gas.md
> +      content: Estimate gas | zkSync Era docs
```suggestion
      content: Estimate Gas | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/dev/how-to/send-message-l2-l1.md
> +      content: Send an L2 to L1 message | zkSync Era docs
```suggestion
      content: Send an L2 to L1 Message | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/dev/how-to/transfer-token-l2.md
> +      content: Transfer a token on L2 | zkSync Era docs
```suggestion
      content: Transfer a Token on L2 | Zksync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/dev/tutorials/README.md
> +      content: Tutorials | zkSync Era docs
```suggestion
      content: Tutorials | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/dev/tutorials/aa-daily-spend-limit.md
> +      content: Daily spending limit account | zkSync Era docs
```suggestion
      content: Daily Spending Limit Account | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/dev/tutorials/api3-usd-paymaster-tutorial.md
> +      content: USDC paymaster tutorial | zkSync Era docs
```suggestion
      content: USDC Paymaster Tutorial | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/dev/tutorials/cross-chain-tutorial.md
> +      content: Cross-chain governance | zkSync Era docs
```suggestion
      content: Cross-Chain Governance | Zksync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/dev/tutorials/custom-aa-tutorial.md
> +      content: Account abstraction multisig | zkSync Era docs
```suggestion
      content: Account Abstraction MultiSig | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/dev/tutorials/custom-paymaster-tutorial.md
> +      content: Building a custom paymaster | zkSync Era docs
```suggestion
      content: Building a Custom Paymaster | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/dev/tutorials/gated-nft-paymaster-tutorial.md
> +      content: Gated NFT paymaster | zkSync Era docs
```suggestion
      content: Gated NFT Paymaster | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/reference/architecture/contract-deployment.md
> +      content: Contract deployment | zkSync Era docs
```suggestion
      content: Contract Deployment | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/reference/architecture/contract-development.md
> +      content: Smart contract development | zkSync Era docs
```suggestion
      content: Smart Contract Development | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/reference/architecture/events.md
> +      content: Handling events | zkSync Era docs
```suggestion
      content: Handling Events | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/reference/architecture/system-contracts.md
> +      content: System contracts | zkSync Era docs
```suggestion
      content: System Contracts | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/reference/concepts/account-abstraction.md
> +      content: Account abstraction | zkSync Era docs
```suggestion
      content: Account Abstraction | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/reference/concepts/blocks.md
> +      content: Blocks | zkSync Era docs
```suggestion
      content: Blocks | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/reference/concepts/bridging-asset.md
> +      content: Bridging assets | zkSync Era docs
```suggestion
      content: Bridging Assets | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/reference/concepts/fee-model.md
> +      content: Fee mechanism | zkSync Era docs
```suggestion
      content: Fee Mechanism | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/reference/concepts/finality.md
> +      content: Finality | zkSync Era docs
```suggestion
      content: Finality | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/reference/concepts/hyperscaling.md
> +      content: Hyperscaling | zkSync Era docs
```suggestion
      content: Hyperscaling | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/reference/concepts/rollups.md
> +      content: Intro to rollups | zkSync Era docs
```suggestion
      content: Intro to Rollups | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/reference/concepts/transactions.md
> +      content: Transactions | zkSync Era docs
```suggestion
      content: Transactions | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/reference/concepts/zkSync.md
> +      content: zkSync Era basics | zkSync Era docs
```suggestion
      content: zkSync Era Basics | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/reference/troubleshooting/README.md
> +      content: Troubleshooting | zkSync Era docs
```suggestion
      content: Troubleshooting | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/reference/troubleshooting/audit-bug-bounty.md
> +      content: Audits and bug bounty program | zkSync Era docs
```suggestion
      content: Audits and Bug Bounty Program | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/reference/troubleshooting/docs-contribution/docs.md
> +      content: Contribute to documentation | zkSync Era docs
```suggestion
      content: Contribute to Documentation | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/reference/troubleshooting/withdrawal-delay.md
> +      content: Withdrawal delay | zkSync Era docs
```suggestion
      content: Withdrawal Delay | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/tools/block-explorer/README.md
> +      content: Block Explorer | zkSync Era docs
```suggestion
      content: Block Explorer | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/tools/block-explorer/block-explorer-menu.md
> +      content: Block explorer menu | zkSync Era docs
```suggestion
      content: Block Explorer Menu | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/tools/block-explorer/contract-verification.md
> +      content: Block explorer contract verification | zkSync Era docs
```suggestion
      content: Block Explorer Contract Verification | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/tools/compiler-toolchain/README.md
> +      content: Compiler toolchain | zkSync Era docs
```suggestion
      content: Compiler Toolchain | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/tools/compiler-toolchain/overview.md
> +      content: Compiler overview | zkSync Era docs
```suggestion
      content: Compiler Overview | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/tools/compiler-toolchain/solidity.md
> +      content: Solidity compiler | zkSync Era docs
```suggestion
      content: Solidity Compiler | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/tools/compiler-toolchain/vyper.md
> +      content: Vyper compiler | zkSync Era docs
```suggestion
      content: Vyper Compiler | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/tools/hardhat/getting-started.md
> +      content: Hardhat getting started | zkSync Era docs
```suggestion
      content: Hardhat Getting Started | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/tools/hardhat/hardhat-zksync-chai-matchers.md
> +      content: hardhat-zksync-chai-matchers | zkSync Era docs
```suggestion
      content: hardhat-zksync-chai-matchers | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/tools/hardhat/hardhat-zksync-deploy.md
> +      content: hardhat-zksync-deploy | zkSync Era docs
```suggestion
      content: hardhat-zksync-deploy | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/tools/hardhat/hardhat-zksync-solc.md
> +      content: hardhat-zksync-solc | zkSync Era docs
```suggestion
      content: hardhat-zksync-solc | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/tools/hardhat/hardhat-zksync-upgradable.md
> +      content: hardhat-zksync-upgradable | zkSync Era docs
```suggestion
      content: hardhat-zksync-upgradable | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/tools/hardhat/hardhat-zksync-vyper.md
> +      content: hardhat-zksync-vyper | zkSync Era docs
```suggestion
      content: hardhat-zksync-vyper | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/tools/hardhat/migrating-to-zksync.md
> +      content: Migration guide | zkSync Era docs
```suggestion
      content: Migration Guide | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/tools/hardhat/plugins.md
> +      content: zkSync Hardhat plugins | zkSync Era docs
```suggestion
      content: zkSync Hardhat Plugins | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/tools/testing/README.md
> +      content: Testing strategies | zkSync Era docs
```suggestion
      content: Testing Strategies | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/tools/testing/dockerized-testing.md
> +      content: Dockerized setup | zkSync Era docs
```suggestion
      content: Dockerized Setup | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/tools/testing/era-test-node.md
> +      content: In-memory node | zkSync Era docs
```suggestion
      content: In-Memory Node | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 commented on docs/tools/zksync-cli/README.md
> +      content: zkSync CLI | zkSync Era docs
```suggestion
      content: zkSync CLI | zkSync Era Docs
```

2023-08-21 11:56 UTC, idea404 requested changes
Some small changes related to grammar 
Might merit looking later into grammar of wider docs

2023-08-22 10:51 UTC, idea404 approved these changes

2023-08-22 12:36 UTC, merged

2023-08-22 12:43 UTC, MexicanAce commented on docs/dev/tutorials/api3-usd-paymaster-tutorial.md
> +      content: USDC Paymaster tutorial | zkSync Era Docs
nit/optional: `tutorial` is not capitalized here, but other titles we have it capitalized