Swift documentation
matter-labs/zksync-web-era-docs pull request #722
Opened 2023-09-27 07:41 UTC by bojan-txfusion

Updated documentation after refactoring.

2023-10-02 13:14 UTC, idea404 approved these changes

2023-10-02 13:25 UTC, idea404 requested changes

2023-10-02 13:25 UTC, idea404 commented on docs/api/swift/paymaster-utils.md
> +Check out the [example](getting-started.md#use-paymaster) how to use paymaster.
This is a broken link, mean to point somewhere else?

2023-10-02 13:25 UTC, idea404 commented on docs/api/swift/features.md
> +zkSync SDK provides a utility method that can be used to get the correctly formed `PaymasterParams` object: [GetPaymasterParams](./paymaster-utils.md#getpaymasterparams).
This is also a broken link, someplace else?

2023-10-02 13:25 UTC, idea404 commented on docs/api/swift/accounts.md
> +[`Connect`](#connect) and [`ConnectL1`](#connectl1), respectively.
These don't lead anywhere. Is this functionality still present?

2023-10-02 13:25 UTC, idea404 commented on docs/api/swift/accounts-l1-l2.md
> +`WalletL1` and `Wallet` objects provide a finalize withdraw workflow. For more information, please refer to the method specification
Is this now only withdraw instead of finalize withdraw?

2024-01-18 16:39 UTC, MexicanAce approved these changes
LGTM (made a bunch of changes/fixes, it's not perfect but it's 99%)

2024-01-18 16:40 UTC, merged