Fix tutorials to support zksync-ethers v6
matter-labs/zksync-web-era-docs pull request #914
Opened 2024-02-14 16:03 UTC by uF4No

# What :computer: 
* Fixing all tutorial scripts to adapt to the breaking changes introduced in `ethers` / `zksync-ethers` v6

# Why :hand:
* Most tutorial scripts are broken due to breaking changes in the new version of the libraries.

# Evidence :camera:
<img width="723" alt="Screenshot 2024-02-14 at 16 02 42" src="https://github.com/matter-labs/zksync-web-era-docs/assets/1957117/b7e48fc5-8a76-46a4-bd56-ee5a88416a70">
![Screenshot 2024-02-14 at 16 03 12](https://github.com/matter-labs/zksync-web-era-docs/assets/1957117/2470edbe-f794-417b-95a8-231d8bab7ed6)

# Notes :memo:
* Any notes/thoughts that the reviewers should know prior to reviewing the code?

2024-02-23 16:50 UTC, Romsters commented on docs/build/tutorials/smart-contract-development/account-abstraction/custom-aa-tutorial.md
> +Make sure you deposit funds on zkSync Era using [on of the available bridges](https://zksync.io/explore#bridges) before running the deployment script.
```suggestion
Make sure you deposit funds on zkSync Era using [one of the available bridges](https://zksync.io/explore#bridges) before running the deployment script.
```

2024-02-23 16:51 UTC, Romsters commented on docs/build/tutorials/smart-contract-development/account-abstraction/custom-aa-tutorial.md
> +  // const multisigAddress = '0x5C9d4d089d25bE4e38356AAe47f880946749C1eA'
Should this commented line be removed?

2024-02-23 16:52 UTC, Romsters commented on docs/build/tutorials/smart-contract-development/account-abstraction/custom-aa-tutorial.md
> +  // const multisigAddress = '0x5C9d4d089d25bE4e38356AAe47f880946749C1eA'
Or is it for reference?

2024-02-23 17:16 UTC, Romsters commented on docs/build/tutorials/smart-contract-development/paymasters/timebased.md
> +    const deployUrl = hardhatConfig.networks.inMemoryNode.url;
Didn't we want Sepolia for paymasters?

2024-02-24 07:19 UTC, uF4No commented on docs/build/tutorials/smart-contract-development/paymasters/erc20fixed.md
> +  const paymasterArtifact = await deployer.loadArtifact("ApprovalPaymaster");
the tutorial uses the paymasters provided by the CLI templates, but it's named ApprovalPaymaster, not ERC20fixedPaymaster. It was not correct before

2024-02-24 07:25 UTC, uF4No commented on docs/build/tutorials/smart-contract-development/paymasters/timebased.md
> +describe.only("TimeBasedPaymaster", function () {
I included it cause the CLI project includes tests and I would don't want to run them as part of the tutorial

2024-03-05 16:51 UTC, JackHamer09 requested changes

2024-03-05 16:51 UTC, JackHamer09 commented on docs/build/tutorials/smart-contract-development/account-abstraction/daily-spend-limit.md
> +Skip the hassle for test ETH by using `zksync-cli` for local testing. Simply execute `npx zksync-cli@latest dev start` to initialize a local zkSync development environment, which includes local Ether
```suggestion
Skip the hassle for test ETH by using `zksync-cli` for local testing. Simply execute `npx zksync-cli dev start` to initialize a local zkSync development environment, which includes local Ethereum and zkSync nodes. This method allows you to test contracts without requesting external testnet funds. Explore more in the [zksync-cli documentation](../../../tooling/zksync-cli/getting-started.md).
```

No need to use @latest. If there are any other occurrencies of that - it should also be removed.

2024-03-05 16:51 UTC, JackHamer09 commented on docs/build/tutorials/smart-contract-development/paymasters/gasless.md
> +npx zksync-cli@latest create gaslessPaymaster
```suggestion
npx zksync-cli create gaslessPaymaster
```

2024-03-05 17:53 UTC, JackHamer09 approved these changes

2024-03-06 10:04 UTC, merged