refactor: improve zk stack block explorer guide pt1
matter-labs/zksync-web-era-docs pull request #949
Opened 2024-02-22 18:17 UTC by zk-Lumi

# What :computer: 
* Remade guide for using block explorer
* Improved wording
* Split into 2 sections -> 1) via docker 2) locally

# Why :hand:
* Part of the guide was inaccurate
* Also this section was quite confusing on how to use block explorer

2024-02-22 18:21 UTC, zk-Lumi commented
Part 1 - This is to update the section on block explorer running locally, wording, and to remove inaccurate description.

Part 2- @githubdoramon will help update the section on block explorer running in docker in coming days.

2024-02-23 09:19 UTC, githubdoramon requested changes
Requesting some small changed

2024-02-23 09:19 UTC, githubdoramon commented on docs/zk-stack/running-a-hyperchain/locally.md
> +Running the `zk server` builds environment and configuration files for block explorer based on your [zksync-era](https://github.com/matter-labs/zksync-era) repo configuration, which you can edit if y
This is not true - running it just runs it, there is nothing related to build config files. Just remove this sentence.

Or, say something like "The server is the main entry point to your hyperchain, and where the block explorer will fetch information to index from"

2024-02-23 09:19 UTC, githubdoramon commented on docs/zk-stack/running-a-hyperchain/locally.md
> +### Running block explorer in docker
Based on the conversation we had in Slack, let's totally remove the docker option

2024-02-23 09:19 UTC, githubdoramon commented on docs/zk-stack/running-a-hyperchain/locally.md
> +Clone & install the block explorer:
the block explorer repository

2024-02-23 09:19 UTC, githubdoramon commented on docs/zk-stack/running-a-hyperchain/locally.md
> +Next you need to set up all the necessary environment and configuration files with your hyperchain settings. You can use a script to build them:
You can use a script to set them up:

2024-03-06 09:28 UTC, githubdoramon approved these changes

2024-03-06 09:28 UTC, merged